/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4.pkg1.visual.partesJugar;

import javax.swing.JLabel;
import practica4.pkg1.Objetos.Juego.Cuadro;

/**
 *
 * @author douglas2021
 */
public class Cuadrito extends javax.swing.JPanel {
    Cuadro cuadro;
    /**
     * Creates new form Cuadrito
     */
    public Cuadrito() {
        initComponents();
        //ficha1.setOpaque(true);
        cuadro = null;
    }

    public JLabel getEnumeracion() {
        return enumeracion;
    }

    public void setEnumeracion(JLabel enumeracion) {
        this.enumeracion = enumeracion;
    }

    public JLabel getFicha1() {
        return ficha1;
    }

    public void setFicha(JLabel ficha) {
        this.ficha1 = ficha;
    }

    public JLabel getLugar() {
        return lugar;
    }

    public void setLugar(JLabel lugar) {
        this.lugar = lugar;
    }

    public JLabel getFicha2() {
        return ficha2;
    }

    public void setFicha2(JLabel ficha2) {
        this.ficha2 = ficha2;
    }

    public JLabel getFicha3() {
        return ficha3;
    }

    public void setFicha3(JLabel ficha3) {
        this.ficha3 = ficha3;
    }

    public JLabel getFicha4() {
        return ficha4;
    }

    public void setFicha4(JLabel ficha4) {
        this.ficha4 = ficha4;
    }

    public Cuadro getCuadro() {
        return cuadro;
    }

    public void setCuadro(Cuadro cuadro) {
        this.cuadro = cuadro;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enumeracion = new javax.swing.JLabel();
        ficha1 = new javax.swing.JLabel();
        lugar = new javax.swing.JLabel();
        ficha2 = new javax.swing.JLabel();
        ficha3 = new javax.swing.JLabel();
        ficha4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 236, 174));
        setPreferredSize(new java.awt.Dimension(30, 30));

        enumeracion.setFont(new java.awt.Font("Ubuntu", 0, 8)); // NOI18N

        ficha1.setFont(new java.awt.Font("Ubuntu", 0, 9)); // NOI18N
        ficha1.setText("Hola Mundo");

        ficha2.setFont(new java.awt.Font("Ubuntu", 0, 9)); // NOI18N
        ficha2.setText("jLabel1");

        ficha3.setFont(new java.awt.Font("Ubuntu", 0, 9)); // NOI18N
        ficha3.setText("jLabel2");

        ficha4.setFont(new java.awt.Font("Ubuntu", 0, 9)); // NOI18N
        ficha4.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enumeracion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ficha4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ficha3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ficha2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enumeracion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(ficha2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ficha3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ficha4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enumeracion;
    private javax.swing.JLabel ficha1;
    private javax.swing.JLabel ficha2;
    private javax.swing.JLabel ficha3;
    private javax.swing.JLabel ficha4;
    private javax.swing.JLabel lugar;
    // End of variables declaration//GEN-END:variables
}
